diff --git a/Dockerfile b/Dockerfile
index 7a44a74a..a17ff886 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-ARG BASE_IMAGE
+ARG BASE_IMAGE=hexpm/elixir:1.16.2-erlang-26.2.1-debian-bookworm-20240130-slim
 
 # Stage 1
 # Builds the Livebook release
@@ -87,6 +87,15 @@ ENV LIVEBOOK_HOME=/data
 # Copy the release build from the previous stage
 COPY --from=build /app/_build/prod/rel/livebook /app
 
+# Copy Livebook apps folder
+COPY apps /app/apps
+
+# Download Academy curriculum
+RUN cd /data \
+    && wget https://github.com/DockYard-Academy/curriculum/archive/refs/tags/V2.0.0.tar.gz \
+    && tar zxf V2.0.0.tar.gz \
+    && rm V2.0.0.tar.gz
+
 # Make release files available to any user, in case someone
 # runs the container with `--user`
 RUN chmod -R go=u /app
